### ISSUE TITLE
Live Example?

### ISSUE THREAD

**Issue by atonb117** [mezerotm/cmv#1]
Hey, you ever get around to making this live or its still living locally?

Would love to talk to you more about CitySDK if you still attending Code for Atlanta's meetups!

**Comment by mezerotm** [comment]
We currently don't have a live example but if you are interested in meeting we have a group meetings at Gwinnett Technical college on Wednesdays at 2pm+, I am currently very busy and have not had time to visit a code for Atlanta meetup but if you are truly interested I do not mind.

**Comment by atonb117** [comment]
Don't sweat it, guy.   Gwinnett is certainly out of my orbit.
