### ISSUE TITLE
Get all four panels working to display some data. 

### ISSUE THREAD

**Issue by ravenusmc** [mezerotm/cmv#13]

**Comment by NJTuley** [comment]
Is this referring to just getting citysdk geoJSON and google maps polygons outputted to all 4 maps? If so, I just got this resolved while working on some other issues with Location input, and code with it working is pushed to the Location_input branch.

**Comment by NJTuley** [comment]
Here is a screenshot of multiple maps working with the data outputted to 2 maps for this example.

![multiple_maps_shown](https://cloud.githubusercontent.com/assets/15338440/23044954/906dcd5a-f470-11e6-9cca-9637f9ca7f3c.GIF)
