### ISSUE TITLE
Get Titles on the maps so that the user will see what they are looking at 

### ISSUE THREAD

**Issue by ravenusmc** [mezerotm/cmv#14]

**Comment by hardnett** [comment]
I have a version where the maps all get dummy titles. What's next is to build something to set the titles when the submit is pressed.

**Comment by hardnett** [comment]
This is blocked by making the pretty printing work #34  and by being able to test with the 4 maps working which is a combination of #33 and #13.

**Comment by hardnett** [comment]
This is done now.
