### ISSUE TITLE
Map needs to be centered when user selects an option to look at 

### ISSUE THREAD

**Issue by ravenusmc** [mezerotm/cmv#17]
Currently, when the user selects an option to look at the map zooms all the way out.

**Comment by mezerotm** [comment]
Got it to [work](https://hastebin.com/vuhufijula.js)!
it also requires [this](https://hastebin.com/uqusequgug.go) to be put in the cmv.js

**Comment by hardnett** [comment]
Awesome!!

Charles R. Hardnett
hardnett@gmail.com

**Comment by ravenusmc** [comment]
This step is done and it just needs to be merged in with the master branch. Changes are currently on Mike_branch.
