### ISSUE TITLE
Add a help page. 

### ISSUE THREAD

**Issue by ravenusmc** [mezerotm/cmv#22]
Currently, there is a button to get help on using the project. However, when it is clicked nothing happens. Thus, a help page should be added explaining how the project works.

**Comment by mezerotm** [comment]
Added a [help page](a299457). But currently, it has no information. It is filled with temporary Lorem Ipson data.

**Comment by hardnett** [comment]
I had a couple of basic ideas:
* a screen shot with annotations of what everything is. 
* a basic workflow showing where the user would go first, the second, etc. 
* an explanation of the variables that can be taken from the census, but made simple for business owners. 
* explanation of settings parameters

**Comment by hardnett** [comment]
I'd also like to suggest that the help be a help.html file that is linked to from the index.html file. Or better yet, make a help directory where you can store any images and other assets as well. This will help to manage the code over time and keep the index.html focused on the navigation of the application and its structure.

**Comment by mezerotm** [comment]
Are you suggesting that the help popup should be an entire page in itself? or that I put the data from help.html into the help popup. I  agree that the help info should be its own file, but that it shouldn't take its own page. And that instead of help.html that it be help.js

**Comment by hardnett** [comment]
Yes, I am suggesting that it be inserted into the popup. At the moment the data is in the index.html file. Whether you do this as a help.js or help.html is up to you. Its just a mater of seperating the data. the popup should still be the method of delivery.

**Comment by mezerotm** [comment]
I currently have an image overlay temporarily, on the master branch I will be working on this more in terms of turning my image into actual code that can be interactive. I will be working on this in a local branch so that I am not constantly pushing to master. When I am done I will do a pull request via this open issue.

**Comment by hardnett** [comment]
okay. I gotcha. I'll pick it up from here. I don't have a task. Let me know what you were planning to do.

**Comment by hardnett** [comment]
I am started using this: http://introjs.com/. Ill have something to push this weekend.
