### ISSUE TITLE
Add a label on the map that shows what the legend/colors mean.

### ISSUE THREAD

**Issue by ravenusmc** [mezerotm/cmv#25]
There has to be a way for the user to see what the legend/colors mean on the map.

**Comment by NJTuley** [comment]
I think that the best way to do this would be to programatically add/alter a legend (add it if there isn't one from a previous map of polygons, alter if there was one) when the user sends a data request to put new polygons on the map. Then the user knows which legend goes with which map, and if no maps have polygons on them yet, then there is no wasted space for legends

**Comment by hardnett** [comment]
I agree Nick. It has to be programmatic. But to keep it simple, I think i'll approach it in the way of always removing the legend and putting up a new one. Since there is a map refresh anyway, this will simplify the management.

**Comment by hardnett** [comment]
This was added with PR #32
