### ISSUE TITLE
Drawing and Shading regions in the map

### ISSUE THREAD

**Issue by hardnett** [mezerotm/cmv#3]
Currently, we have the long & lat coords for the points around a region. However, we need to figure out how to draw the edge of a region such as a tract. Then we can shade it in. The demonstration code on the City SDK can be our first start:

[Geo Request](http://uscensusbureau.github.io/citysdk/examples/geoRequest)

I have  feeling that we will have to dig into their code to understand how they trace and shade in-order to write our customized tracing and shading to get the heat-map effect. 

There are other map examples for us to look at:
[Container Geometry](http://uscensusbureau.github.io/citysdk/examples/containerGeometry/)
[Drawing on an Arbitrary region](http://esridc.github.io/citysdk-hud/google-maps.html)

**Comment by ravenusmc** [comment]
I have started to work some on getting the information to appear on the map. However, the site runs very very slow for me! Anyone else having this issue?

**Comment by ravenusmc** [comment]
I should say that it was not just map data that was taking long-about 30 seconds to a minute but even attempting to look at the console. Hopefully it was something that just happened once!

**Comment by ravenusmc** [comment]
This line census.geoRequest(request, geoCallBack); in the api.js file-does it pull all of the lat, long coordinates? I have noticed that if I comment it out nothing works. Or is it just because of the geoCallBack function within it that is what stringify's the response?

**Comment by hardnett** [comment]
This is done. I am not sure why it was still open. :)
