### ISSUE TITLE
Choosing a Domain Name

### ISSUE THREAD

**Issue by hardnett** [mezerotm/cmv#43]
We need to pick a domain name for the application. 

I have already checked and cmv.org, cmv.info are taken at this time. I am thinking that a .info domain is the best for what our app does. 

I throw out an idea:  censusmapvis.info

any ideas?

**Comment by ravenusmc** [comment]
Is censusmap taken? I think that censusmapvis is also pretty good. I am assuming that the vis stands for visual?

**Comment by hardnett** [comment]
censusmap.info is available, but censusmap.org is not. Someone has parked it. So someone else may end up using the .org version, which is not a bad thing unless we don't want to be confused with another site. 

The vis = visualization 

We could also do something like censusvisualer.info. By not saying map, then we give the impression of having several visualizations and not solely map visualization.

**Comment by NJTuley** [comment]
we could also do something like visualcensus.info or visualcensus.org , again it doesn't limit us to the maps, but it gets across the part about census visualization and etc.

**Comment by hardnett** [comment]
unfortunately, visualcensus.org is taken

https://www.godaddy.com/whois/results.aspx?recaptchaResponse=03AI-r6f4I-mW8ay-QZtiBBEKwCmRliEmY0jh5FLUijWqhBVEzGf0QBVzcKBypFuqxcM85g-9Xn4zTG2KdShYbkYcEvz04fvGS3Zm8ODxSdBfV_-EG2dSZzi3rwhdXeYfGkrR-EqKG60sivn50w3Jh8B70HHeOjNeYjUliL5rJLnJYvrURt_eRDReUtJANHhZ09luWE4UWk5bWoGzZSJNPLp6D2xFNYOv4OsbuP0ycLisr7rurwRXfm7fCos9xOpEBCERBssbEh808un34Uw4vALuZ-21ldAqrBZQYRglA5rqur9G1IJYXhe7cCkc_Wzn6xswEpLlVyFTQ6g_3TK8Rpab3eWlFv3HYIT2RfHVzdGFnXwJK38wU11KR3T3s0kQdgBZgs0IRJKr_fYCl5FajYhLodbloHLh1vQ&domain=visualcensus.org&isc=cjcbh99&prog_id=GoDaddy&pl_id=1

It refers to this site: http://visualcens.us

which was developed by Florida State University. It looks a lot like what we are doing from the examples. But I think ours is cooler :). Theirs actually looks like an API that is used in several different tools. It may be worth investigating more down the road, but I would not want to focus any time on learning about them now because their scope seems larger than ours technologically. Although they seem to only be focused on Florida as a test case.

**Comment by NJTuley** [comment]
could we go with something like graphicalcensus? or is that too much of a mouthful?

**Comment by ravenusmc** [comment]
Although graphicalcensus is good I do think it is a mouthful, it almost sounds like a dinosaur name! The name though does get the point across of what this project does though.

**Comment by ravenusmc** [comment]
Is visualcensus.info taken? I know that org was. Or visual-US-census.org?

**Comment by NJTuley** [comment]
maybe visualcens-US.info or .org?

**Comment by ravenusmc** [comment]
visualcens-US is also okay. However, I wonder how many people will not what cens means!

**Comment by hardnett** [comment]
visualcensus.info I believe is available. We don't need the US; top-level domains like info, com, edu, org etc are implicitly info.us,edu.us, and com.us. Other countries have suffixes to separate them from the implicit US domains.

**Comment by NJTuley** [comment]
ok, so do we want to go with visualcensus.info then?

**Comment by ravenusmc** [comment]
I once heard that Facebook spent 300 man hours designing their logo. Although a name is important we could spend forever debating one! I think that visualcensus is good and it has my vote!

**Comment by NJTuley** [comment]
So are we at a consensus then for the name?

**Comment by hardnett** [comment]
Looks like visualcensus.info is the winner. So I will go ahead and purchase that.
