### ISSUE TITLE
Fix color range

### ISSUE THREAD

**Issue by NJTuley** [mezerotm/cmv#47]
The minimum value in our color ranges is almost transparent. We need to change it to where the minimum value, although lighter than the other values (definitely the lightest), it should still be plainly visible. Whether this is done by putting a thin border around all polygons, or just making the minimum color value a bit darker and easier to see

**Comment by hardnett** [comment]
I think this is essentially just choosing a new color palette for the shades. This is the current code: 

cmv.js
```
// Step 1: Determines the array of colors
		// todo: find a way to pragmatically change the tint/shade
		let colors = ['#FEEDDE', '#FDBE85', '#FD8D3C', '#E6550D', '#A63603'];
```
Do we need more colors?

**Comment by NJTuley** [comment]
One consideration to keep in mind is to be sure that the minimum for the new range is clearly visible (not necessarily dark, just visible)

**Comment by NJTuley** [comment]
Also, do we want to have multiple color palettes for the different maps? Just so that all of the maps do not have their data drawn with the same palette?

**Comment by hardnett** [comment]
Having it visible is still primary. 

Having different palettes for different maps is a good idea. That can be dealt with in the beta release as separate issue.

**Comment by NJTuley** [comment]
Fixed the color range and added a few other colors in for variation's sake (so all of the maps are not all one color range)
![colors](https://cloud.githubusercontent.com/assets/15338440/24209612/234c9bfa-0efd-11e7-9934-ec84d524f37b.GIF)
