### ISSUE TITLE
Turn off debug messages for end user version

### ISSUE THREAD

**Issue by NJTuley** [mezerotm/cmv#50]
We don't want regular users being able to view all of the debug messages about inner workings of the program, so we need to turn these off for the production/hosted version of the program

**Comment by mezerotm** [comment]
well hopefully if we used [cmv.debugger.debug](https://github.com/mezerotm/cmv/blob/master/js/documentation.js#L33) correctly it's as easy as toggling that to false ;) - eitherway i'll go through and do this real quick!

**Comment by mezerotm** [comment]
4efca277c8ed3eb8cd3fae47b5493d83f6eebffc
