### ISSUE TITLE
Initial map load is not centering on current location

### ISSUE THREAD

**Issue by hardnett** [mezerotm/cmv#56]
I was noticing this while in Boulder. The location textbox is updated properly with the correct zip code and city. However, the map always centers on Atlanta.  See below.

![screen shot 2017-04-21 at 12 45 13 am](https://cloud.githubusercontent.com/assets/2136554/25265785/9e9b81da-263c-11e7-8ece-6cafe9f07e5a.png)

**Comment by mezerotm** [comment]
I think this might be a hardcod, although I thought we fixed that.

**Comment by NJTuley** [comment]
Made a few changes to previous code, and it works now.

**Comment by mezerotm** [comment]
@NJTuley is referring to 23a184e
