### ISSUE TITLE
While a map loads, the user is able to select another map

### ISSUE THREAD

**Issue by hardnett** [mezerotm/cmv#58]
I had 4 maps loaded, but I suspect this would be the case with 2 maps. I selected a map and then a variable and clicked submit. The spinning wheel started, and then I clicked on another map. The data was loaded into the second map, and it was incomplete. The legend and title loaded, but the polygons did not show.

**Comment by NJTuley** [comment]
Had to flag whether a map is currently being populated with a request, but after I did this it is correct now
